#name: CICD Pipeline for news app
# This is using dagger for prevent github action changes for break down the pipeline
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
  #  build-and-deploy:
    #    runs-on: ubuntu-latest
    #    steps:
      #      - name: Checkout repository
        #        uses: actions/checkout@v3
        #
      #      - name: Setup Dagger
        #        uses: dagger/dagger-for-github@8.0.0
        #        with:
          #          install-only: true
          #          version: "latest"  # semver x.y.z
          #
      #      - name: Install backend dependencies into runner
        #        run: |
          #          cd backend
          #          npm install
          #          npm ci
        #
      #      - name: Setup Node.js
        #        uses: actions/setup-node@v3
        #        with:
          #          node-version: '20'
          #          #         cache: 'npm'
          #          cache-dependency-path: 'backend/package-lock.json'
          #
      #      - name: Run Dagger pipeline from root
        #        run: |
          #          npm install --save-dev @dagger.io/dagger
          #          dagger run -- node backend/cicd.mjs
        #        env:
          #          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
