name: CICD Pipeline for News App
# This uses Dagger to prevent GitHub Action changes from breaking the pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install backend dependencies into runner
        run: |
          cd backend
          npm install

      # Start and use docker for delivery

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile  # Add this line if your Dockerfile has a custom name or location
          push: true
          tags: josepepedev/news_backend:latest
          cache-from: type=registry,ref=josepepedev/news_backend:latest
          cache-to: type=inline

      # Start and use dagger (not available yet)
      
      #- name: Setup Dagger
        #uses: dagger/dagger-for-github@8.0.0
        #with:
          #install-only: true
          #version: "latest"  # semver x.y.z

      #- name: Run Dagger pipeline from root
        #run: |
          #npm install --save-dev @dagger.io/dagger
          #dagger run -- node backend/cicd.mjs
        #env:
          #RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
